name: ci
on: [push, pull_request]

jobs:
  skeleton:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Debug workspace
        run: |
          echo "PWD: $(pwd)"
          echo "Workspace: $GITHUB_WORKSPACE"
          ls -la
          echo "--- contents of ml/ ---"
          ls -la ml || true

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        working-directory: ${{ github.workspace }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - run: echo "CI skeleton ok"
